### ISSUE TITLE
Alt tag

### ISSUE THREAD

**Issue by TessaViergever** [gitazeinstra/your-tribe-profile-card#4]
https://github.com/gitazeinstra/your-tribe-profile-card/blob/fb5cf22a5f38c5f65607bc9cbfb835fb3792fa7a/index.html#L19

Een <img> heeft een alt tag nodig. Hierin omschrijf je wat er in de afbeelding te zien is. Dit is belangrijk voor de afbeelding niet kan laden of als iemand met een visuele beperking de website bezoekt en gebruik maakt van een screenreader.

**Comment by gitazeinstra** [comment]
Gefixt, dankjewel voor je feedback :)

**Comment by gitazeinstra** [comment]
Gefixt, dankjewel voor je feedback :)
